# Generated by Django 5.0 on 2023-12-27 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0002_alter_job_description_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="job",
            name="uuid_ref",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("00000000-0000-0000-0000-000000000000"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid_ref",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("00000000-0000-0000-0000-000000000000"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
