# Generated by Django 5.0 on 2023-12-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0002_user_job_delete_choice_delete_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(
                blank=True, help_text="Job description", max_length=350
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True),
        ),
    ]
