# Generated by Django 5.0 on 2023-12-27 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0003_remove_job_id_remove_user_id_job_uuid_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="uuid_ref",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid_ref",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
