# Generated by Django 5.0 on 2023-12-27 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0004_alter_job_uuid_ref_alter_user_uuid_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="user_id",
            new_name="user",
        ),
    ]
