# Generated by Django 5.0 on 2023-12-27 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0005_rename_user_id_job_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="uuid_ref",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="uuid_ref",
            new_name="uuid",
        ),
    ]
