# Generated by Django 5.0 on 2023-12-27 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0006_rename_uuid_ref_job_uuid_rename_uuid_ref_user_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="uuid",
            new_name="uuid_ref",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="uuid",
            new_name="uuid_ref",
        ),
    ]
