# Generated by Django 5.0 on 2023-12-27 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0007_rename_uuid_job_uuid_ref_rename_uuid_user_uuid_ref"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["user"], "verbose_name_plural": "Jobs"},
        ),
    ]
